// Byte-emitted source for a dynamically traced VM basic block.
// Executed extent: [0x58C85B6B, 0x58C85BFE), 147 bytes; not a function boundary.
extern "C" __declspec(naked) void VMHandler_58c85b6b() {
    __asm {
        __asm _emit 0x0f
        __asm _emit 0xb6
        __asm _emit 0x44
        __asm _emit 0x25
        __asm _emit 0x00
        __asm _emit 0xf5
        __asm _emit 0xd2
        __asm _emit 0xf6
        __asm _emit 0x8d
        __asm _emit 0xad
        __asm _emit 0x01
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x32
        __asm _emit 0xc3
        __asm _emit 0xc0
        __asm _emit 0xde
        __asm _emit 0x06
        __asm _emit 0xf9
        __asm _emit 0xd0
        __asm _emit 0xc0
        __asm _emit 0x04
        __asm _emit 0xcf
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xba
        __asm _emit 0xe2
        __asm _emit 0x7d
        __asm _emit 0xf5
        __asm _emit 0xd0
        __asm _emit 0xc0
        __asm _emit 0x2c
        __asm _emit 0xae
        __asm _emit 0x32
        __asm _emit 0xd8
        __asm _emit 0xd2
        __asm _emit 0xe2
        __asm _emit 0x8b
        __asm _emit 0x14
        __asm _emit 0x04
        __asm _emit 0x0f
        __asm _emit 0xc9
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xb3
        __asm _emit 0xf9
        __asm _emit 0x81
        __asm _emit 0xef
        __asm _emit 0x04
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x66
        __asm _emit 0xf7
        __asm _emit 0xc7
        __asm _emit 0x8f
        __asm _emit 0x08
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xbe
        __asm _emit 0xcf
        __asm _emit 0x66
        __asm _emit 0xb9
        __asm _emit 0x70
        __asm _emit 0x45
        __asm _emit 0x89
        __asm _emit 0x17
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xc1
        __asm _emit 0xc9
        __asm _emit 0x8b
        __asm _emit 0x4c
        __asm _emit 0x25
        __asm _emit 0x00
        __asm _emit 0x8d
        __asm _emit 0xad
        __asm _emit 0x04
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0xf9
        __asm _emit 0x66
        __asm _emit 0x3b
        __asm _emit 0xf3
        __asm _emit 0xf7
        __asm _emit 0xc2
        __asm _emit 0xb2
        __asm _emit 0x58
        __asm _emit 0x62
        __asm _emit 0x2f
        __asm _emit 0x33
        __asm _emit 0xcb
        __asm _emit 0x81
        __asm _emit 0xf1
        __asm _emit 0xd3
        __asm _emit 0x22
        __asm _emit 0x11
        __asm _emit 0x6f
        __asm _emit 0xf9
        __asm _emit 0xf5
        __asm _emit 0xc1
        __asm _emit 0xc1
        __asm _emit 0x03
        __asm _emit 0x66
        __asm _emit 0x81
        __asm _emit 0xf9
        __asm _emit 0xb3
        __asm _emit 0x58
        __asm _emit 0xf7
        __asm _emit 0xd9
        __asm _emit 0x81
        __asm _emit 0xe9
        __asm _emit 0xde
        __asm _emit 0x5c
        __asm _emit 0x95
        __asm _emit 0x4a
        __asm _emit 0xf6
        __asm _emit 0xc7
        __asm _emit 0x23
        __asm _emit 0xf9
        __asm _emit 0xf7
        __asm _emit 0xd9
        __asm _emit 0x81
        __asm _emit 0xc1
        __asm _emit 0xc0
        __asm _emit 0x12
        __asm _emit 0xb8
        __asm _emit 0x60
        __asm _emit 0x3b
        __asm _emit 0xe8
        __asm _emit 0x81
        __asm _emit 0xfc
        __asm _emit 0x65
        __asm _emit 0x03
        __asm _emit 0x84
        __asm _emit 0x32
        __asm _emit 0x33
        __asm _emit 0xd9
        __asm _emit 0x03
        __asm _emit 0xf1
        __asm _emit 0xe9
        __asm _emit 0x4d
        __asm _emit 0x2c
        __asm _emit 0x01
        __asm _emit 0x00
    }
}
