// Byte-emitted source for a dynamically traced VM basic block.
// Executed extent: [0x58C0E4F5, 0x58C0E53A), 69 bytes; not a function boundary.
extern "C" __declspec(naked) void VMHandler_58c0e4f5() {
    __asm {
        __asm _emit 0x8b
        __asm _emit 0x0f
        __asm _emit 0xf9
        __asm _emit 0x66
        __asm _emit 0x23
        __asm _emit 0xd4
        __asm _emit 0x8b
        __asm _emit 0x57
        __asm _emit 0x04
        __asm _emit 0x03
        __asm _emit 0xca
        __asm _emit 0x66
        __asm _emit 0x8b
        __asm _emit 0xc4
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xc8
        __asm _emit 0xc6
        __asm _emit 0xc4
        __asm _emit 0xbb
        __asm _emit 0x89
        __asm _emit 0x4f
        __asm _emit 0x04
        __asm _emit 0x9c
        __asm _emit 0x66
        __asm _emit 0x0f
        __asm _emit 0xac
        __asm _emit 0xd0
        __asm _emit 0xb1
        __asm _emit 0x66
        __asm _emit 0x98
        __asm _emit 0x66
        __asm _emit 0xd3
        __asm _emit 0xc8
        __asm _emit 0x8f
        __asm _emit 0x07
        __asm _emit 0x8b
        __asm _emit 0x44
        __asm _emit 0x25
        __asm _emit 0x00
        __asm _emit 0x81
        __asm _emit 0xc5
        __asm _emit 0x04
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0x00
        __asm _emit 0xf8
        __asm _emit 0xf9
        __asm _emit 0x33
        __asm _emit 0xc3
        __asm _emit 0x35
        __asm _emit 0x18
        __asm _emit 0x1e
        __asm _emit 0xd1
        __asm _emit 0x6f
        __asm _emit 0x2d
        __asm _emit 0xb3
        __asm _emit 0x38
        __asm _emit 0x7d
        __asm _emit 0x13
        __asm _emit 0xc1
        __asm _emit 0xc0
        __asm _emit 0x03
        __asm _emit 0xf9
        __asm _emit 0xe9
        __asm _emit 0x04
        __asm _emit 0xca
        __asm _emit 0x17
        __asm _emit 0x00
    }
}
